
version: '3.8'

services:
  societyshield:
    build:
      context: .
      args:
        - GEMINI_API_KEY=${GEMINI_API_KEY}
    container_name: societyshield_app
    ports:
      - "3000:80"
    restart: always
    networks:
      - security_net

networks:
  security_net:
    driver: bridge
